name: nuretool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  university_repository:
    path: ./packages/university_repository
  tasks_repository:
    path: ./packages/tasks_repository
  cist_api:
    path: ./packages/cist_api
  drift_db:
    path: ./packages/drift_db
  events_api:
    path: ./packages/events_api
  groups_api:
    path: ./packages/groups_api
  teachers_api:
    path: ./packages/teachers_api
  rooms_api:
    path: ./packages/rooms_api
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  bloc: ^9.0.0
  meta: ^1.16.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_lint: 0.2.0-dev.0

flutter:
  uses-material-design: true
  generate: true
