name: nuretool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  university_repository:
    path: ./packages/university_repository
  tasks_repository:
    path: ./packages/tasks_repository
  cist_api:
    path: ./packages/cist_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
