name: cist_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  groups_api:
    path: ../groups_api
  events_api:
    path: ../events_api
  enough_convert: ^1.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
