name: events_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  events_api:
    path: ../events_api
  groups_api:
    path: ../groups_api
  teachers_api:
    path: ../teachers_api
  cist_api:
    path: ../cist_api
  local_db_api:
    path: ../local_db_api
  rxdart: ^0.28.0
  equatable: ^2.0.7
  meta: ^1.16.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
